[package]
name = "mullvad-paths"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Mullvad VPN application paths and directories"
license = "GPL-3.0"
edition = "2018"

[dependencies]
error-chain = "0.12"
log = "0.4"

[target.'cfg(any(windows, target_os = "macos"))'.dependencies]
dirs = "1.0"
