[package]
name = "talpid-ipc"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "IPC client and server for talpid"
license = "GPL-3.0"
edition = "2018"

[dependencies]
error-chain = "0.12"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-pubsub = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-ipc-server = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
tokio = "0.1"
futures = "0.1"

jsonrpc-client-core = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "e9dbdc80" }
jsonrpc-client-ipc = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "e9dbdc80" }

[dev-dependencies]
assert_matches = "1.0"
env_logger = "0.5"
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
uuid = { version = "0.6", features = ["v4"] }
futures = "0.1.23"
tokio = "0.1"
