[package]
name = "mullvad-rpc"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Mullvad VPN RPC clients. Providing an interface to query our infrastructure for information."
license = "GPL-3.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
error-chain = "0.12"
futures = "0.1.15"
jsonrpc-client-core = "0.5"
jsonrpc-client-http = "0.5"
lazy_static = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
hyper = "0.11"
hyper-openssl = "0.5"
tokio-service = "0.1"
tokio-openssl = "0.2"
log = "0.4"

mullvad-types = { path = "../mullvad-types" }

[dev-dependencies]
filetime = "0.1"
tempfile = "3.0"
